In [142]:
pip install sklearn

In [18]:
pip install pandas

Note: you may need to restart the kernel to use updated packages.


In [19]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [20]:
pip install gradio

Note: you may need to restart the kernel to use updated packages.


In [143]:

import gradio as gr

In [144]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import model_selection
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier

from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler

from sklearn.model_selection import StratifiedShuffleSplit

from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier, VotingClassifier
from sklearn.linear_model import SGDClassifier

from sklearn.model_selection import cross_val_predict, RandomizedSearchCV, train_test_split, GridSearchCV
from sklearn.metrics import classification_report, PrecisionRecallDisplay, RocCurveDisplay, accuracy_score, confusion_matrix, ConfusionMatrixDisplay


from sklearn.pipeline import Pipeline
from sklearn.metrics import classification_report
from sklearn.metrics import roc_auc_score, accuracy_score, precision_score, recall_score, f1_score
from sklearn.metrics import confusion_matrix, precision_recall_curve, auc, roc_curve, recall_score, classification_report, f1_score



In [145]:
import warnings
warnings.filterwarnings('ignore')

In [146]:
names = ['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']
dataFrame=pd.read_csv('pima-indians-diabetes.csv', names = names)
array=dataFrame.values
X=array[:,0:8]
y = array[:,8]


In [147]:
dataFrame.values

array([[  6.   , 148.   ,  72.   , ...,   0.627,  50.   ,   1.   ],
       [  1.   ,  85.   ,  66.   , ...,   0.351,  31.   ,   0.   ],
       [  8.   , 183.   ,  64.   , ...,   0.672,  32.   ,   1.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,   0.245,  30.   ,   0.   ],
       [  1.   , 126.   ,  60.   , ...,   0.349,  47.   ,   1.   ],
       [  1.   ,  93.   ,  70.   , ...,   0.315,  23.   ,   0.   ]])

In [84]:
y

array([1., 0., 1., 0., 1., 0., 1., 0., 1., 1., 0., 1., 0., 1., 1., 1., 1.,
       1., 0., 1., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0., 0., 1., 0., 0.,
       0., 0., 0., 1., 1., 1., 0., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0.,
       0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0.,
       0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1.,
       0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 1., 1., 1., 0., 0.,
       0., 1., 0., 0., 0., 1., 1., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       0., 1., 1., 0., 0., 0., 1., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0.,
       1., 1., 0., 0., 0., 1., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 1.,
       1., 1., 1., 0., 0., 1., 1., 0., 1., 0., 1., 1., 1., 0., 0., 0., 0.,
       0., 0., 1., 1., 0., 1., 0., 0., 0., 1., 1., 1., 1., 0., 1., 1., 1.,
       1., 0., 0., 0., 0.

In [148]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.3, stratify=y, random_state=42)

In [149]:
from sklearn.preprocessing import StandardScaler

#instantiate StandardScaler object
stdscaler = StandardScaler()
stdscaler.fit(X_train)
X_train_scaled = stdscaler.transform(X_train)
X_test_scaled = stdscaler.transform(X_test)


In [150]:
df_xs = pd.DataFrame(X_train_scaled)
df_xs.describe()

0             1             2             3             4  \
count  5.370000e+02  5.370000e+02  5.370000e+02  5.370000e+02  5.370000e+02   
mean   4.202101e-17  1.157774e-17 -2.034375e-16  1.020289e-16  4.486376e-17   
std    1.000932e+00  1.000932e+00  1.000932e+00  1.000932e+00  1.000932e+00   
min   -1.160056e+00 -3.867386e+00 -3.633274e+00 -1.316902e+00 -7.223922e-01   
25%   -8.612793e-01 -7.008219e-01 -3.753633e-01 -1.316902e+00 -7.223922e-01   
50%   -2.637251e-01 -1.250830e-01  1.501062e-01  1.672714e-01 -3.725540e-01   
75%    6.326063e-01  6.425690e-01  5.704817e-01  7.480349e-01  4.744230e-01   
max    3.919155e+00  2.465742e+00  2.777453e+00  2.554855e+00  6.127073e+00   

                  5             6             7  
count  5.370000e+02  5.370000e+02  5.370000e+02  
mean   2.220239e-15 -5.520103e-16 -2.260761e-16  
std    1.000932e+00  1.000932e+00  1.000932e+00  
min   -4.120071e+00 -1.183876e+00 -1.065138e+00  
25%   -5.685772e-01 -7.002091e-01 -8.105476e-01  
50%    3.402295e-02 -2.852109e-01 -3.013676e-01  
75%    5.468741e-01  4.910448e-01  6.321291e-01  
max    4.483007e+00  5.518793e+00  4.026663e+00

In [151]:
knn = KNeighborsClassifier()
knn_params =  {'n_neighbors': list(range(1, 50,2))}
knn_grid = GridSearchCV(knn,knn_params, cv = 5, scoring = 'accuracy')
knn_grid.fit(X_train_scaled,y_train)

GridSearchCV(cv=5, estimator=KNeighborsClassifier(),
             param_grid={'n_neighbors': [1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21,
                                         23, 25, 27, 29, 31, 33, 35, 37, 39, 41,
                                         43, 45, 47, 49]},
             scoring='accuracy')

In [152]:
print(knn_grid.best_params_)
{'n_neighbors':29}

{'n_neighbors': 29}


{'n_neighbors': 29}

In [153]:
results=[]
grid_predictions=knn_grid.predict(X_test_scaled)
# print classification report
print(classification_report(y_test,grid_predictions))

accur=knn_grid.score(X_test_scaled, y_test)
print(f'knn accuracy is {accur}')
results.append(accur)

              precision    recall  f1-score   support

         0.0       0.74      0.90      0.81       150
         1.0       0.69      0.41      0.51        81

    accuracy                           0.73       231
   macro avg       0.71      0.65      0.66       231
weighted avg       0.72      0.73      0.71       231

knn accuracy is 0.7272727272727273


In [159]:
X_new_test =np.array([[2,500,100,20,100,20,0.5,30],[2,197,70,45,543,30.5,0.158,53],[1,189,60,23,846,30.1,0.398,59],[8,179,72,42,130,32.7,0.719,36]])
stdscaler.fit(X_new)
X_new_test_scaled = stdscaler.transform(X_new)
y_pred = knn_grid.predict(X_new_scaled)

In [160]:
X_new_test_scaled
y_pred


array([0., 0., 0., 1.])

In [157]:
print(dataFrame.columns)

Index(['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class'], dtype='object')


In [169]:
def predict_pregnancies_glucose_bp_skinthickness_insulin_bmi_dpf_age(pregnancies, glucose, bp, skinthickness, insulin, bmi, dpf, age):
    # Scale the input values
    input_data = stdscaler.transform([[pregnancies, glucose, bp, skinthickness, insulin, bmi, dpf, age]])

    # Make the prediction
    prediction = knn_grid.predict(input_data)[0]

    # Return the prediction
    return "Diabetic" if prediction == 1 else "Non-Diabetic"

# Define the input and output interfaces
inputs = [
    gr.inputs.Number(label="Number of Pregnancies"),
    gr.inputs.Number(label="Glucose Level"),
    gr.inputs.Number(label="Blood Pressure"),
    gr.inputs.Number(label="Skin Thickness"),
    gr.inputs.Number(label="Insulin Level"),
    gr.inputs.Number(label="BMI"),
    gr.inputs.Number(label="Diabetes Pedigree Function"),
    gr.inputs.Number(label="Age")
]
outputs = gr.outputs.Textbox(label="Prediction")

# Create a Gradio interface and launch it
gr.Interface(fn=predict_pregnancies_glucose_bp_skinthickness_insulin_bmi_dpf_age, inputs=inputs, outputs=outputs, title="Diabetes Predictor").launch(share = True)


Running on local URL:  http://127.0.0.1:7880

Could not create share link. Please check your internet connection or our status page: https://status.gradio.app
